package org.example.testcodesample.mock;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.concurrent.atomic.AtomicLong;
import org.example.testcodesample.post.domain.Post;
import org.example.testcodesample.post.service.port.PostRepository;

public class FakePostRepository implements PostRepository {

    private final AtomicLong autoGeneratedId = new AtomicLong(0);
    private final List<Post> data = new ArrayList<>();

    @Override
    public Optional<Post> findById(long id) {
        return data.stream()
            .filter(user -> user.getId().equals(id))
            .findAny();
    }

    @Override
    public Post save(Post post) {

        if (post.getId() == null || post.getId() == 0) {
            Post newPost = Post.builder()
                .id(autoGeneratedId.incrementAndGet())
                .content(post.getContent())
                .createdAt(post.getCreatedAt())
                .modifiedAt(post.getModifiedAt())
                .writer(post.getWriter())
                .build();
            data.add(newPost);
            return newPost;
        } else {
            data.removeIf(it -> it.getId().equals(post.getId()));
            data.add(post);
            return post;
        }
    }
}
